### ISSUE TITLE
Crash on `addrStr` use

### ISSUE THREAD

**Issue by OstlerDev** [oipwg/insight-websocket-service#1]
```
[2018-08-02T23:11:48.835Z] warn: Node is stopping, gently closing the database. Please wait, this could take a while.
[2018-08-02T23:11:48.835Z] info: Stopping insight-websocket-service
[2018-08-02T23:11:48.876Z] info: Stopping flosight-ui
[2018-08-02T23:11:48.876Z] error: uncaught exception: TypeError: Cannot read property 'addrStr' of undefined
    at node.services.address.getAddressSummary (/home/floc/flocore/testnet/node_modules/insight-websocket-service/src/index.js:94:47)
    at /home/floc/flocore/testnet/node_modules/flocore-node/lib/services/address/index.js:141:14
    at /home/floc/flocore/testnet/node_modules/flocore-node/lib/services/address/index.js:96:16
    at /home/floc/flocore/testnet/node_modules/async/dist/async.js:1140:9
    at /home/floc/flocore/testnet/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/home/floc/flocore/testnet/node_modules/async/dist/async.js:988:17)
    at /home/floc/flocore/testnet/node_modules/async/dist/async.js:969:16
    at /home/floc/flocore/testnet/node_modules/async/dist/async.js:1137:13
    at /home/floc/flocore/testnet/node_modules/flocore-node/lib/services/address/index.js:415:18
    at /home/floc/flocore/testnet/node_modules/flocore-node/lib/services/mempool/index.js:272:14
[2018-08-02T23:11:48.876Z] error: TypeError: Cannot read property 'addrStr' of undefined
    at node.services.address.getAddressSummary (/home/floc/flocore/testnet/node_modules/insight-websocket-service/src/index.js:94:47)
    at /home/floc/flocore/testnet/node_modules/flocore-node/lib/services/address/index.js:141:14
    at /home/floc/flocore/testnet/node_modules/flocore-node/lib/services/address/index.js:96:16
    at /home/floc/flocore/testnet/node_modules/async/dist/async.js:1140:9
    at /home/floc/flocore/testnet/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/home/floc/flocore/testnet/node_modules/async/dist/async.js:988:17)
    at /home/floc/flocore/testnet/node_modules/async/dist/async.js:969:16
    at /home/floc/flocore/testnet/node_modules/async/dist/async.js:1137:13
    at /home/floc/flocore/testnet/node_modules/flocore-node/lib/services/address/index.js:415:18
    at /home/floc/flocore/testnet/node_modules/flocore-node/lib/services/mempool/index.js:272:14
[2018-08-02T23:11:48.876Z] info: Beginning shutdown
```

**Comment by OstlerDev** [comment]
This should be fixed in 34cebb3b146b83d83dc36e698e2071267e371da3
